### ISSUE TITLE
修改model_type参数

### ISSUE THREAD

**Issue by mazx21** [hellen9527/Pytorch-Chinese-Text-Classification#1]
修改model_type参数之后，跑的结果没什么变化是什么原因呢？

**Comment by yuye2133** [comment]
> 修改model_type参数之后，跑的结果没什么变化是什么原因呢？

运行了哪个脚本呢，model_type改了什么
如果运行没有错误，看下loss是否在正常下降

**Comment by mazx21** [comment]
运行了run_dnn_cls.python，在run_dnn_cls.sh中修改了model_type，把cnn换成模型fasttext之后，再运行跑出来的结果没变化，还是cnn的结果，这是什么原因呢？

**Comment by yuye2133** [comment]
> 运行了run_dnn_cls.python，在run_dnn_cls.sh中修改了model_type，把cnn换成模型fasttext之后，再运行跑出来的结果没变化，还是cnn的结果，这是什么原因呢？

你贴一下运行的日志输出吧，我看下什么情况

**Comment by mazx21** [comment]
[Evaluating] 25/25 [==============================] 237.6ms/stepTest Loss:  0.15,  Test Acc: 96.23%
Precision, Recall and F1-Score...
              precision    recall  f1-score   support

          差评     0.9780    0.8843    0.9288       856
          好评     0.9570    0.9923    0.9743      2220

    accuracy                         0.9623      3076
   macro avg     0.9675    0.9383    0.9516      3076
weighted avg     0.9628    0.9623    0.9617      3076

Confusion Matrix...
[[ 757   99]
 [  17 2203]]

Process finished with exit code 0
就是换了模型之后，不管是cnn、lstm、 fasttext， 运行的结果都是这个

**Comment by mazx21** [comment]
还是参数没修改合适，现在解决了，谢谢你哈。

**Comment by yuye2133** [comment]
> 还是参数没修改合适，现在解决了，谢谢你哈。

好的，不客气，那我把问题关了。
