### ISSUE TITLE
数据集格式问题

### ISSUE THREAD

**Issue by mazx21** [hellen9527/Pytorch-Chinese-Text-Classification#2]
![微信图片_20240121224546](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/105896608/1fc442e7-f755-43eb-a964-2a00efe31204)
![微信图片_20240121224556](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/105896608/e084ebdd-f000-4c31-875a-0e6119357e00)
您好，我想问一下我修改了我自己的数据集格式，运行代码的时候还是有问题，能帮我看看这是什么原因嘛？

**Comment by yuye2133** [comment]
看起来有一行你不是json格式的，你的文件每一行都用json.dumps({"你的数据":1}, ensure_ascii=False)保存；
另外还可以在text_classify.py的第288行，json.loads()那里，还是try，防止你的数据处理有问题
