### ISSUE TITLE
多分类应用

### ISSUE THREAD

**Issue by mazx21** [hellen9527/Pytorch-Chinese-Text-Classification#3]
作者您好，我想问一下这个代码可以应用于三分类问题吗？如何改呢？

**Comment by yuye2133** [comment]
可以的，你把labels.txt文件改一下就好了，你有几个类别，文件里就几行，每行是这个类别的名称

**Comment by mazx21** [comment]
![微信图片_20240124163859](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/105896608/ffb9cb48-aa4d-48c0-a2e0-b3cdd4c4c712)改了之后出这个错是什么原因呢

**Comment by mazx21** [comment]
![微信图片_20240130092950](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/105896608/0fa5d7d4-7bb1-46d7-9c80-9dc0e02db6f7)
labels.txt文件改为三分类的类别了，还需要修改什么参数吗

**Comment by yuye2133** [comment]
> ![微信图片_20240130092950](https://private-user-images.githubusercontent.com/105896608/300650692-0fa5d7d4-7bb1-46d7-9c80-9dc0e02db6f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1Nzk5NjAsIm5iZiI6MTcwNjU3OTY2MCwicGF0aCI6Ii8xMDU4OTY2MDgvMzAwNjUwNjkyLTBmYTVkN2Q0LTdiYjEtNDZkNy05YzgwLTlkYzBlMDJkYjZmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwMTU0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGUxNzg1NGQ4YzEzMWY2NWU3Y2M5MDdiYzUyNTU1YzIzNTQwODJiMDlhZmMyNWRiZjUyZmQ0NzFjZDlmOTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qzqk5_kAnMVvO7--u7FSMuvYc8SLEgv_kol_LYHqTg4) labels.txt文件改为三分类的类别了，还需要修改什么参数吗

你前面那个“好评”的错误怎么解决的啊，另外你在221行前面把：predict_all和labels_all，还有label_list打印一点出来看下；看错误是越界了

**Comment by mazx21** [comment]
好评的错误原因还是你自己的数据集没处理合适的原因吧，train、dev、test都需要处理，然后把labels.txt改为自己的标签
