### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by crazyzhihao** [hellen9527/Pytorch-Chinese-Text-Classification#6]
您好，dataset文件夹中并没有cache文件，这是我的报错信息！
![微信图片_20240407145512](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/64fa9fe1-9b36-4f0f-96f7-16dd2d356938)

**Comment by hellen9527** [comment]
把你的启动命令发一下，我看看用的哪个模型出的问题，然后再贴一两行你的训练数据文件

**Comment by crazyzhihao** [comment]
![微信图片_20240407150113](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/e98b49e1-b613-484f-9254-c5c254f5cc03)
![微信图片_20240407150048](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/4d83407c-9b20-475a-8811-9edfae356a55)
我是用的是lr，第一张中是我调试的内容

**Comment by crazyzhihao** [comment]
![微信图片_20240407150232](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/86201821-ffb6-416b-b0de-9c87dcb2b98f)
zh
![微信图片_20240407150113](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/0a707366-c162-4ca2-8dd0-85f15b2c771c)
我使用的是lr模型，下面是我的调试内容

**Comment by crazyzhihao** [comment]
主要是在加载数据集的时候，没有加载进去

**Comment by hellen9527** [comment]
看起来确实没有读到文件，你是用的我的数据还是你自己的数据呢

**Comment by crazyzhihao** [comment]
您的数据！jd的数据

**Comment by hellen9527** [comment]
我这边测试了一下好像没问题，看起来是文件路径不全；你是用Linux系统吗，尝试下打印args.data_dir是否正确，run_ml_cls.py文件的第102行加上print(args.data_dir)；

**Comment by crazyzhihao** [comment]
是linux系统的，刚刚我试了一下，文件路径是没有问题的，指向的就是datasets
![Uploading 微信图片_20240407151846.png…]()

**Comment by crazyzhihao** [comment]
是linux系统的，刚刚我试了一下，文件路径是没有问题的，指向的就是datasets
![微信图片_20240407151846](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/17485825-5680-43bd-8861-7e883db7925c)

**Comment by hellen9527** [comment]
抱歉，我的问题，默认的data_format参数应该是json，才看到你用的是ltw，这种是用\t的，两个字段，第一个字段是words，第二个是label才用ltw，这份数据是json格式的。

**Comment by crazyzhihao** [comment]
需要修改一下run_ml_cls.sh中的ltw->json是吧

**Comment by hellen9527** [comment]
是的

**Comment by crazyzhihao** [comment]
好嘞！已经成功了！谢谢您的帮助！

**Comment by hellen9527** [comment]
不客气，欢迎star,follow, 后面有问题可以直接在git提，看到我都会及时回复，这个我先close
