### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by crazyzhihao** [hellen9527/Pytorch-Chinese-Text-Classification#7]
在做深度学习的实验时，这次又出现了空，
![empty](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/af7dad5b-a57c-44ed-a3cb-df580fe8fa60)

**Comment by yuye2133** [comment]
空的话应该是数据加载失败了，打印一下加载数据那里看看读取了多少条数据

**Comment by crazyzhihao** [comment]
![微信图片_20240416205944](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/81fe4dc1-05bd-430e-b87e-8c3f183e2b25)
这里加载的数据是空的

**Comment by hellen9527** [comment]
> ![微信图片_20240416205944](https://private-user-images.githubusercontent.com/103234521/322851338-81fe4dc1-05bd-430e-b87e-8c3f183e2b25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzI4MzIsIm5iZiI6MTcxMzI3MjUzMiwicGF0aCI6Ii8xMDMyMzQ1MjEvMzIyODUxMzM4LTgxZmU0ZGMxLTA1YmQtNDMwZS1iODdlLThjM2YxODNlMmIyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMzAyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2M4Y2QzMzYyZWUzZTM4YjVmYWU1NGE1NGMxYzBjM2IwY2RhMDFmOWNmNWJiY2JlM2VmNWQwMTJmMzBkNzVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.umGvVJsfn4Fs22UGU93PphM-Wr5CzkUJa7yaham3jBA) 这里加载的数据是空的

贴一下你的启动命令，用的数据是自己的还是我的数据

**Comment by crazyzhihao** [comment]
用的是您的数据，启动命令如下
![1](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/a47c90f3-6602-4c37-8437-933bf97c1eba)
![2](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/f89cda7b-acd3-44f8-b653-2accc1cf9af9)

**Comment by crazyzhihao** [comment]
用的是您的数据，启动命令如下
![1](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/c1e56cd0-89c8-4ea7-b8cb-8ed087bb17a3)
![2](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/b4af3379-d7f6-483c-b600-b687108377af)

**Comment by hellen9527** [comment]
> 用的是您的数据，启动命令如下 ![1](https://private-user-images.githubusercontent.com/103234521/322853321-c1e56cd0-89c8-4ea7-b8cb-8ed087bb17a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzU1MDEsIm5iZiI6MTcxMzI3NTIwMSwicGF0aCI6Ii8xMDMyMzQ1MjEvMzIyODUzMzIxLWMxZTU2Y2QwLTg5YzgtNGVhNy1iOGNiLThlZDA4N2JiMTdhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMzQ2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDczNGVmMmMxOGQwZjMzMzBhOGY1ZDhkZGE3MTNjMjJiMTc2OTAxN2U2MjJlNjNmOTQ0NGI0ODRlODJiNTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GzH1KFIWheT9t1AbmH6Jx4BD4iZQDOyoSvC7AZ1djlY) ![2](https://private-user-images.githubusercontent.com/103234521/322853332-b4af3379-d7f6-483c-b600-b687108377af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzU1MDEsIm5iZiI6MTcxMzI3NTIwMSwicGF0aCI6Ii8xMDMyMzQ1MjEvMzIyODUzMzMyLWI0YWYzMzc5LWQ3ZjYtNDgzYy1iNjAwLWI2ODcxMDgzNzdhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMzQ2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzNiMGZjYzZiZGY2ODg1YTQxNTcxMWZjZTZlODVjOTNkODFhZTA4MDMxZTgyNjM5NmU0OGI3YjI5ZmE5NWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M9MbCHozVcNMAZmVxxLYsbDM9a0mueRGGTdocpclU1o)

很奇怪，我重新git clone 这个项目，然后用 bash scripts/run_dnn_cls.sh 启动，可以正常跑到这个地方，没啥问题，你要不试下在一个新的目录下重新拷贝项目运行试试，如果还有问题，把完整打印的日志贴一下
![image](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/144710795/14880c63-806b-4450-a7e5-7cdffce93ddd)
