### ISSUE TITLE
bert

### ISSUE THREAD

**Issue by crazyzhihao** [hellen9527/Pytorch-Chinese-Text-Classification#8]
您好，这里bert是不是需要自己先下载下来，还是在代码里面自动下载了呀？
![微信图片_20240410212605](https://github.com/hellen9527/Pytorch-Chinese-Text-Classification/assets/103234521/47f50f3c-bcf2-4fae-a4d3-18d8954cf7ef)

**Comment by yuye2133** [comment]
是需要下载bert-base-chinese放在项目根目录下，下载链接：https://huggingface.co/google-bert/bert-base-chinese；可以用git clone https://huggingface.co/google-bert/bert-base-chinese
